import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans, Playfair_Display } from "next/font/google";
import Footer from "@/components/Footer";
import { ScrollToTop } from "@/utils/ScrollToTop";
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  display: "swap",
  weight: ["400", "600", "700"],
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${nunitoSans.variable} ${playfairDisplay.variable} antialiased`}
      >
        <ScrollToTop />
        {children}
        <Footer />
      </body>
    </html>
  );
}
